export const ThemeColors = {
  default: 1,
  themes: [
    {
      id: 1,
      name: "Classic Blue",
      foundationColor: "#0D47A1",
      backgroundColor: "#E3F2FD",
      foreColor: "#FFFFFF",
      primaryColor: "#2196F3",
      secondaryColor: "#64B5F6",
    },
    {
      id: 2,
      name: "Sunset Orange",
      foundationColor: "#FF6F00",
      backgroundColor: "#FFF3E0",
      foreColor: "#212121",
      primaryColor: "#FF9800",
      secondaryColor: "#FFB74D",
    },
    {
      id: 3,
      name: "Emerald Green",
      foundationColor: "#004D40",
      backgroundColor: "#E0F2F1",
      foreColor: "#FFFFFF",
      primaryColor: "#009688",
      secondaryColor: "#4DB6AC",
    },
    {
      id: 4,
      name: "Royal Purple",
      foundationColor: "#311B92",
      backgroundColor: "#EDE7F6",
      foreColor: "#FFFFFF",
      primaryColor: "#673AB7",
      secondaryColor: "#9575CD",
    },
    {
      id: 5,
      name: "Soft Pink",
      foundationColor: "#880E4F",
      backgroundColor: "#FCE4EC",
      foreColor: "#212121",
      primaryColor: "#E91E63",
      secondaryColor: "#F48FB1",
    },
    {
      id: 6,
      name: "Golden Yellow",
      foundationColor: "#FF8F00",
      backgroundColor: "#FFFDE7",
      foreColor: "#212121",
      primaryColor: "#FFC107",
      secondaryColor: "#FFD54F",
    },
    {
      id: 7,
      name: "Ocean Teal",
      foundationColor: "#006064",
      backgroundColor: "#E0F7FA",
      foreColor: "#FFFFFF",
      primaryColor: "#00BCD4",
      secondaryColor: "#4DD0E1",
    },
    {
      id: 8,
      name: "Charcoal Gray",
      foundationColor: "#263238",
      backgroundColor: "#CFD8DC",
      foreColor: "#FFFFFF",
      primaryColor: "#607D8B",
      secondaryColor: "#90A4AE",
    },
    {
      id: 9,
      name: "Ruby Red",
      foundationColor: "#B71C1C",
      backgroundColor: "#FFEBEE",
      foreColor: "#FFFFFF",
      primaryColor: "#F44336",
      secondaryColor: "#EF9A9A",
    },
    {
      id: 10,
      name: "Citrus Lime",
      foundationColor: "#33691E",
      backgroundColor: "#F1F8E9",
      foreColor: "#212121",
      primaryColor: "#8BC34A",
      secondaryColor: "#AED581",
    },
  ],
};
